# Generated by Django 3.0.4 on 2020-03-20 12:47

from django.db import migrations, models
import ui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=ui.models.upload)),
            ],
        ),
    ]
